### PR TITLE
[ci skip] An effort to document: Entry guide to contributors

### PR DESCRIPTION
**Pull request by Sumith1896**
To improve the documentation of SymEngine, an entry guide to future contributors also to increase understanding of SymEngine as part of GSoC community bonding.

### CODE REVIEW

**Comment by debugger22** [comment]
+1. Nice initiative!

**Comment by abinashmeher999** [comment]
@Sumith1896 Nice initiative! +1

**Comment by aktech** [comment]
+1
Probably, it's one the most important thing SymEngine need to broaden it's community.

**Comment by Sumith1896** [comment]
@certik Why don't we have a wiki option in the SymEngine repo?

**Comment by abinashmeher999** [comment]
@Sumith1896 Also add a section on libraries that we use, and why we use it.

**Comment by Sumith1896** [comment]
@abinashmeher999 I was wondering about using the Wiki option in SymEngine. That'll be open for all and much easier to maintain.
But SymEngine doesn't have a Wiki option, maybe because SymPy does.
Any ideas?

**Comment by abinashmeher999** [comment]
@Sumith1896 I am part of an org. There is a repo whose wiki is empty, and only I can see the option to navigate to that section. And it doesn't appear to one of my friends who is not a part of that org. I think a wiki is visible only to the owners when it is empty. We can't see it unless a page is added to it. After a page is added then we can view the option to navigate there. After that we should automatically see a wiki in our fork of the repo. I am not sure how to send pull requests to a wiki. We should try after @certik has added a homepage to the wiki. Anyway, we can always send patches if we can't figure a way to send pull requests.

**Comment by OrkoHunter** [comment]
> I am not sure how to send pull requests to a wiki.

Wiki pages are open to be *edited* by people. After the one wiki page is created by owners (or maybe collaborators), anyone would be able to edit or create new pages.

**Comment by certik** [comment]
I created the wiki pages here: https://github.com/sympy/symengine/wiki, sorry for the delay.

**Comment by Sumith1896** [comment]
I'm closing this. Maintaining wiki section is a lot easier and cleaner than committing a markdown file.
Thanks for the info.
Cheers

**Pull request closed without merging**
