### PR TITLE
Make Teuchos stacktraces work with Catch

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Thanks! Can you post an example of an exception in the tests?

**Comment by isuruf** [comment]
Aborts are working fine. 
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_functions is a Catch v1.1 b14 (develop) host application.
Run with -? for options

-------------------------------------------------------------------------------
Sin: functions
-------------------------------------------------------------------------------
/home/isuru/projects/csympy/symengine/tests/basic/test_functions.cpp:93
...............................................................................

/home/isuru/projects/csympy/symengine/tests/basic/test_functions.cpp:93: FAILED:
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal
  Traceback (most recent call last):
    File unknown, in _start()
    File "/build/buildd/glibc-2.19/csu/libc-start.c", line 287, in
  __libc_start_main()
    File "/home/isuru/projects/csympy/symengine/catch/catch.cpp", line 19, in
  main()
      int result = Catch::Session().run( argc, argv );
    File "/home/isuru/projects/csympy/symengine/catch/catch.hpp", line 5662, in
  Catch::Session::run(int, char* const*)
      returnCode = run();
    File "/home/isuru/projects/csympy/symengine/catch/catch.hpp", line 5682, in
  Catch::Session::run()
      return static_cast<int>( runner.runTests().assertions.failed );
    File "/home/isuru/projects/csympy/symengine/catch/catch.hpp", line 5551, in
  Catch::Runner::runTests()
      totals += context.runTest( *it );
    File "/home/isuru/projects/csympy/symengine/catch/catch.hpp", line 5230, in
  Catch::RunContext::runTest(Catch::TestCase const&)
      runCurrentTest( redirectedCout, redirectedCerr );
    File "/home/isuru/projects/csympy/symengine/catch/catch.hpp", line 5393, in
  Catch::RunContext::runCurrentTest(std::string&, std::string&)
      invokeActiveTestCase();
    File "/home/isuru/projects/csympy/symengine/catch/catch.hpp", line 5421, in
  Catch::RunContext::invokeActiveTestCase()
      m_activeTestCase->invoke();
    File "/home/isuru/projects/csympy/symengine/catch/catch.hpp", line 6727, in
  Catch::TestCase::invoke() const
      test->invoke();
    File "/home/isuru/projects/csympy/symengine/catch/catch.hpp", line 5822, in
  Catch::FreeFunctionTestCase::invoke() const
      m_fun();
    File "/home/isuru/projects/csympy/symengine/tests/basic/test_functions.cpp"
  , line 107, in ____C_A_T_C_H____T_E_S_T____93()
      r1 = sin(x);
    File "/home/isuru/projects/csympy/symengine/functions.cpp", line 328, in
  SymEngine::sin(Teuchos::RCP<SymEngine::Basic const> const&)
      abort();
    File "/build/buildd/glibc-2.19/stdlib/abort.c", line 89, in __GI_abort()
    File "/build/buildd/glibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise
  .c", line 56, in __GI_raise()
    File unknown, in killpg()
  

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed
```

Exceptions do not work. I'll fix that also

**Comment by certik** [comment]
Perfect.

**Comment by isuruf** [comment]
Aborts and segfaults work fine, but exceptions will take some work, because all exceptions are caught and we need to print the correct stacktrace.

**Comment by certik** [comment]
Thanks for this. I think it looks good.

**Pull request merged**
