### PR TITLE
PEP 3149

### LINKED ISSUE #604: Non-conforming naming of Python extension module shared object (PEP 3149)
I guess this is related to how CMake is configured to build the extension module.
On my Ubuntu 14.04 machine, running cmake with `-DPYTHON_BIN=python3.4m` and then building produces a shared object file named: `symengine_wrapper.so`.
I would however expect the file to be named: `symengine_wrapper.cpython-34m.so`.

Reference: [PEP 3149](https://www.python.org/dev/peps/pep-3149/)

### PR DESCRIPTION
**Pull request by isuruf**
Fixes #604 

This PR changes the name of the python wrappers according to PEP 3149 when the variable `get_config_var('SOABI')` is defined on non-Windows systems.

cc @bjodah

### CODE REVIEW

**Comment by bjodah** [comment]
I am completely new to CMake so I might not be the best person to review this I'm afraid.

**Comment by certik** [comment]
The change is fine, but then you also need to change all imports in Python.

**Comment by certik** [comment]
So @bjodah said [here](https://github.com/sympy/symengine/issues/604#issuecomment-146350775) that the Python import doesn't change, but the change should only be made in Python 3.4. For some reason, even Python 3.4 fails on Travis, so we need to investigate.

**Comment by isuruf** [comment]
It was an issue with the `setup.py` file. Fixed in 300e7a6

**Comment by certik** [comment]
Excellent, that works. +1 to merge.

**Pull request merged**
