### PR TITLE
[WIP] Test MSVC support via Appveyor

### PR DESCRIPTION
**Pull request by certik**
This is just an initial PR to get something working, we'll polish the cmake later.

### CODE REVIEW

**Comment by certik** [comment]
Here is a build log: https://gist.github.com/certik/d98b8a0ab0c24a1f6734, it doesn't find GMP. 

@isuruf I know you tried AppVeyor before, how did you install GMP?

**Comment by isuruf** [comment]
I used `mingw-get` to install GMP. It won't work for MSVC

**Comment by certik** [comment]
@isuruf why not? The C ABI should be compatible. After we fix #478, then I think it should be working. Until then, the gmpxx will not work, I agree.

I found this: http://devpacks.com/nuget/package/libgmp_vc120, I just need to figure out how to install it.

**Comment by isuruf** [comment]
Are you testing this on Windows or at Appveyor? I can help via gitter.

**Comment by certik** [comment]
I am testing this at appveyor.

**Comment by certik** [comment]
Closing in favor of #544.

**Pull request closed without merging**
