### PR TITLE
Add MPFR as a Piranha dependency

### PR DESCRIPTION
**Pull request by Sumith1896**
@certik @isuruf

### CODE REVIEW

**Comment by certik** [comment]
+1.

**Comment by Sumith1896** [comment]
Shippable build was restarted, it passes here: https://app.shippable.com/builds/5588f32527cb5b0c00c55c4c

**Comment by Sumith1896** [comment]
Good to merge.

**Comment by Sumith1896** [comment]
Good to merge. @certik

**Comment by certik** [comment]
Shippable fails, but it seems an internal Shippable problem.

**Comment by Sumith1896** [comment]
Thanks for merging.

**Pull request merged**
