### PR TITLE
Rename CSymPy to SymEngine

### PR DESCRIPTION
**Pull request by certik**
This only renames things in text files. No code is touched yet.

### CODE REVIEW

**Comment by pbrady** [comment]
Why?

**Comment by certik** [comment]
Because CSymPy is a terrible name for a pure C++ library, and even worse name for a Julia library (with no Python in it). SymEngine is the name of the C++ library now, and CSymPy are just the Python wrappers. We do not have a name for the Julia wrappers yet.

**Comment by pbrady** [comment]
Makes a lot of sense.  +1

**Comment by certik** [comment]
The first test passed on Travis (https://travis-ci.org/sympy/symengine/builds/61645391), the second commit only affects README, so I am merging.

**Pull request merged**
