### PR TITLE
Renaming CSymPy to SymEngine, other cleanups

### PR DESCRIPTION
**Pull request by Sumith1896**
Following changes made
* Renaming, last traces of CSymPy, hopefully
* Update Readme
* CMake message given for the tests and benchmarks

cc @certik @isuruf @thilinarmtb

### CODE REVIEW

**Comment by certik** [comment]
+1 if tests pass.

**Comment by isuruf** [comment]
@certik, although I've added the option `BUILD_TESTS`, `BUILD_TESTING` is the standard way. Should we change it?

**Comment by isuruf** [comment]
+1

**Comment by Sumith1896** [comment]
@certik @isuruf Can we get this merged?

**Comment by certik** [comment]
Isuru can you merge it?

**Comment by Sumith1896** [comment]
Thanks for merging!

**Pull request merged**
