### PR TITLE
Make all tests pass with Teuchos::RCP, enable it on Travis and Shippable

### LINKED ISSUE #450: Figure out how to use Teuchos::RCP in Debug mode
The `Teuchos::RCP` provides 100% safety in Debug mode (our own `RCP` implementation is not 100% safe in Debug mode --- it can't find dangling pointers). However, we currently use a self reference idiom in SymEngine:
```c++
RCP<const Log> self = rcp_const_cast<Log>(rcp(this));
```
We should create a function or a macro, that returns `RCP<const X> self` for a class `X`. The reason is that this idiom is the only place, where `Teuchos::RCP` would not work as a drop in replacement (since Teuchos does not store the refcount in our class). However, there is a way to use `Teuchos::RCP` for this idiom too, one has to add some member variables into the class, perhaps a weak `RCP` pointer to itself, or something like that. This would be done in Debug mode only. In Release mode, we will continue using our own fast implementation.

### PR DESCRIPTION
**Pull request by certik**
Fixes #450

Now the standard recommendation for development is to use both `-DWITH_SYMENGINE_ASSERT=yes` and `-DWITH_SYMENGINE_RCP=no`, then the code should never segfault or have undefined behavior. The flag `CMAKE_BUILD_TYPE` (`Release` or `Debug`) is only used for compiler optimization options --- for bigger calculations that behave weird, one can keep the `Release` build type, but still turn on the `-DWITH_SYMENGINE_ASSERT=yes` and `-DWITH_SYMENGINE_RCP=no` options, which will make the code 100% safe. I updated the README.

### CODE REVIEW

**Comment by certik** [comment]
There are couple of failures on Travis. This failure:
```
+g++ -std=c++0x -I/home/travis/our_usr/include/ -L/home/travis/our_usr/lib test_basic.cpp -lsymengine -lteuchos -lbfd -lgmpxx -lgmp

In file included from /home/travis/our_usr/include/symengine/basic.h:25:0,

                 from test_basic.cpp:4:

/home/travis/our_usr/include/symengine/symengine_rcp.h:17:27: fatal error: Teuchos_RCP.hpp: No such file or directory

compilation terminated.
```
should be fixed by ed7b2190e3099d92735a1f8d0235fa6bd6eb103e. 

I have to investigate the following failure:
```
symengine.tests.test_arit.test_expand2 ... ok

symengine.tests.test_arit.test_expand3 ... ok

symengine.tests.test_arit.test_args ... ok

symengine.tests.test_arit.test_free_symbols ... terminate called after throwing an instance of 'Teuchos::NullReferenceError'

  what():  /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_RCPNode.cpp:720:

Throw number = 1

Throw test that evaluated to true: true

Teuchos::RCP<SymEngine::Basic const> : You can not call operator->() or operator*() if getRawPtr()==0!

Abort caught. Printing stacktrace:

Traceback (most recent call last):

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/classobject.c", line 2602, in instancemethod_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4348, in ext_do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4253, in do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/typeobject.c", line 5449, in slot_tp_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/classobject.c", line 2602, in instancemethod_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4348, in ext_do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4253, in do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/typeobject.c", line 5449, in slot_tp_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/classobject.c", line 2602, in instancemethod_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4348, in ext_do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4253, in do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/typeobject.c", line 5449, in slot_tp_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/classobject.c", line 2602, in instancemethod_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4348, in ext_do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4253, in do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/typeobject.c", line 5449, in slot_tp_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/classobject.c", line 2602, in instancemethod_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4348, in ext_do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4121, in call_function()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4253, in do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/typeobject.c", line 5449, in slot_tp_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/classobject.c", line 2602, in instancemethod_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4348, in ext_do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4121, in call_function()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 4348, in ext_do_call()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/funcobject.c", line 526, in function_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3267, in PyEval_EvalCodeEx()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 2271, in PyEval_EvalFrameEx()

  File "-------src-dir-------/Python-2.7.10/Objects/object.c", line 1439, in _PyObject_GenericGetAttrWithDict()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2561, in call_function_tail()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "-------src-dir-------/Python-2.7.10/Objects/descrobject.c", line 247, in methoddescr_call()

  File "-------src-dir-------/Python-2.7.10/Python/ceval.c", line 3904, in PyEval_CallObjectWithKeywords()

  File "-------src-dir-------/Python-2.7.10/Objects/abstract.c", line 2529, in PyObject_Call()

  File "/home/travis/build/certik/symengine/symengine/python/symengine/lib/symengine_wrapper.cpp", line 7700, in __pyx_pw_9symengine_3lib_17symengine_wrapper_5Basic_39free_symbols()

    __pyx_r = __pyx_pf_9symengine_3lib_17symengine_wrapper_5Basic_38free_symbols(((struct __pyx_obj_9symengine_3lib_17symengine_wrapper_Basic *)__pyx_v_self));

  File "/home/travis/build/certik/symengine/symengine/python/symengine/lib/symengine_wrapper.cpp", line 7754, in __pyx_pf_9symengine_3lib_17symengine_wrapper_5Basic_38free_symbols()

    __pyx_t_5 = __pyx_f_9symengine_3lib_17symengine_wrapper_c2py(((SymEngine::RCP<SymEngine::Basic const > )((SymEngine::RCP<SymEngine::Basic const > )__pyx_7genexpr__pyx_v_elem))); if (unlikely(!__pyx_t_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 248; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  File "/home/travis/build/certik/symengine/symengine/python/symengine/lib/symengine_wrapper.cpp", line 2050, in __pyx_f_9symengine_3lib_17symengine_wrapper_c2py()

    __pyx_t_1 = (SymEngine::is_a<SymEngine::Add>((*__pyx_v_o)) != 0);

  File "/home/travis/build/certik/symengine/symengine/teuchos/Teuchos_RCP.hpp", line 356, in Teuchos::RCP<SymEngine::Basic const>::operator*() const

    debug_assert_not_null();

  File "/home/travis/build/certik/symengine/symengine/teuchos/Teuchos_RCPDecl.hpp", line 820, in Teuchos::RCP<SymEngine::Basic const>::debug_assert_not_null() const

    assert_not_null();

  File "/home/travis/build/certik/symengine/symengine/teuchos/Teuchos_RCP.hpp", line 515, in Teuchos::RCP<SymEngine::Basic const>::assert_not_null() const

    throw_null_ptr_error(typeName(*this));

  File "/home/travis/build/certik/symengine/symengine/teuchos/Teuchos_RCPNode.cpp", line 717, in Teuchos::throw_null_ptr_error(std::string const&)

    TEUCHOS_TEST_FOR_EXCEPTION(

  File unknown, in __cxa_throw()

  File unknown, in std::terminate()

  File unknown, in std::rethrow_exception(std::__exception_ptr::exception_ptr)

  File unknown, in __gnu_cxx::__verbose_terminate_handler()

  File unknown, in abort()

  File unknown, in raise()

  File unknown, in killpg()

  File "/home/travis/build/certik/symengine/symengine/teuchos/Teuchos_stacktrace.cpp", line 449, in loc_abort_callback_print_stack()

    Teuchos::show_stacktrace();

Done.

bin/test_travis.sh: line 92:  4538 Aborted                 nosetests -v
```
```

**Comment by certik** [comment]
Then there is also some kind of a clang error (https://travis-ci.org/certik/symengine/jobs/68341285, https://travis-ci.org/certik/symengine/jobs/68341287):
```
[  1%] Building CXX object symengine/teuchos/CMakeFiles/teuchos.dir/Teuchos_dyn_cast.cpp.o

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_dyn_cast.cpp:42:

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_dyn_cast.hpp:46:

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_TypeNameTraits.hpp:50:

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_ConstTypeTraits.hpp:46:

In file included from /home/travis/build/certik/symengine/symengine/teuchos/Teuchos_ConfigDefs.hpp:86:

In file included from /usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/cmath:46:

In file included from /usr/include/math.h:427:

/usr/include/x86_64-linux-gnu/bits/math-finite.h:177:1: error: unknown type name

      '__extern_always_inline'

__extern_always_inline double __NTH (lgamma (double __d))

^
```
Not sure what causes that.

**Comment by certik** [comment]
Ok, all tests pass now, except one clang test (I posted the error above). It's the same error as reported here: https://groups.google.com/d/topic/travis-ci/iy4tXzwgtsE/discussion, unfortunately with no workaround.

**Comment by certik** [comment]
This is ready for review, all old tests pass, few more other tests were added to Travis (one of them commented out due to #486).

**Comment by isuruf** [comment]
+1 to merge. We'll figure out #486 after this is i

**Comment by certik** [comment]
We should merge Sumith's PR first. I agree about fixing #486 later.

**Comment by isuruf** [comment]
We need to rebase this.

**Comment by certik** [comment]
This was rebased and merged in #499.

**Pull request closed without merging**
