### PR TITLE
eval_mpfr method added

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Looks good. I think we should also set the MPFR precision in the upper
level function and use this precision throughout.

**Comment by isuruf** [comment]
I didn't set it because the user could give the precision by initializing `mpfr_t` in `eval_mpfr(mpfr_t result, const Basic &b, mpfr_rnd_t rnd);` with the necessary precision.

**Comment by certik** [comment]
Ah, yes, that's the way to go. Add some tests with various precisions, to make this clear. Now when we have this, we can for example take some more difficult example (I know there is one, where the answer looks like an integer, or 167.99999 to be precise, and then after like 15 digits you get something other than 9). We can evaluate with our `eval_double` and then check the answer with `eval_mpfr` as well as show that higher precision provides more accurate result. I'll try to lookup the example.

**Comment by Sumith1896** [comment]
Does this come as a cmake option?

**Comment by isuruf** [comment]
@certik, I added a test. Is this what you had in mind? (I'll add more tests)
@Sumith1896 yes, `-DWITH_MPFR=yes` to enable it or if you have arb, just `-DWITH_ARB=yes`

**Comment by certik** [comment]
@isuruf Yes, exactly. I think you need to merge with master, there are some conflicts.

**Comment by isuruf** [comment]
Merged with master and improved the comments. Please check if I missed something in the comments.

**Comment by certik** [comment]
This is very good. +1 to merge.

**Pull request merged**
