### PR TITLE
Test Sage wrappers

### PR DESCRIPTION
**Pull request by isuruf**
Testing of sage wrappers in travis with sage ubuntu package.

Installing sage using the ppa sometimes fail. So, installing is tried 3 times, but it still fails sometimes.

### CODE REVIEW

**Comment by isuruf** [comment]
Shall I add this test to the `allow_failures` category?

**Comment by certik** [comment]
Looks good. Tests seem to pass. Why would this go into allow failures?

**Comment by isuruf** [comment]
Installing sage fails very often in my fork, and you saw it on sympy too. That's why I wanted to move it to allow_failures

**Comment by certik** [comment]
I see. Yes, move it there for now until we figure out a solid workaround.

**Comment by certik** [comment]
This looks good. Thanks. +1 to merge.

**Comment by certik** [comment]
If Sage fails to install, how exactly does it fail? We can also just install the binary by downloading and unpacking a binary tarball.

**Comment by certik** [comment]
It would be nice to have something that works 100%.

**Comment by isuruf** [comment]
I tried using a binary tarball. It always fails. Maybe it takes too much memory to unpack.

If sage fails to install, it will try 2 more times. If that doesn't work either, then it will fail when `sage` command is invoked.

**Comment by certik** [comment]
It might run out of disk space. Would it fail while downloading or while unpacking and with what error?

One can unpack while downloading using pipes or something, to save disk space.

**Pull request merged**
