### PR TITLE
Added a beginner IRuby notebook

### PR DESCRIPTION
**Pull request by abinashmeher999**
- Added an IRuby notebook for beginners
- Added a README redirecting to instructions on setting up IRuby
- Added `iruby` as a development dependency

### CODE REVIEW

**Comment by abinashmeher999** [comment]
@dilcom Could you please review this? I would like to have your suggestions. :blush:

**Comment by dilcom** [comment]
Sure =)

It doesn't seem good to call ```#to_s``` each time to output value to iRuby. You can define ```#to_iruby``` method as alias of ```#to_s``` and iRuby should call it. You may also take a look how iRuby supported in [GnuplotRB](https://github.com/dilcom/gnuplotrb/blob/master/lib/gnuplotrb/mixins/iruby.rb) and Daniel's [advices](https://github.com/SciRuby/iruby/pull/37).

I'm also not sure if you should add iRuby as dependency.

Apart of this I think notebook is ok since only Symbols work.

**Comment by abinashmeher999** [comment]
Thanks for the suggestions! :smile:  I looked at your repo. It's a great idea to have a separate `Gemfile` for the notebooks. It's to isolate the dependencies of notebooks from the dependencies of the gem, right? 

Also, `iruby` requires ruby version 2.1 or higher. So, the build breaks for versions lower than that. It should not be included as a dependency in a sense that it is not essential for development. Better to adopt your method. I will try out the `#to_iruby` approach, and let you know how that goes.

**Comment by dilcom** [comment]
Since you don't test your gem with iruby, there is no need to add it to dependencies.

Additional gemfile is needed because otherwise ruby will use main gemfile. There is no iruby in it so ruby will be unable to find it and notebook will not work.

**Comment by abinashmeher999** [comment]
@dilcom Thanks for the review and the suggestion! :smile: . @certik The PR is ready. :sparkles:

**Comment by abinashmeher999** [comment]
@certik This PR can be merged too.

**Comment by certik** [comment]
I think that works. Thanks!

**Pull request merged**
