### PR TITLE
ComplexDouble

### PR DESCRIPTION
**Pull request by isuruf**
This class would keep a `std::complex<double>`
I implemented some not implemented methods in `RealDouble` as well.
For eg. now `1+2*I + 0.2` gives `1.2 + 2.0*I`.
This way, the fact that the imaginary part is exact is lost though.

### CODE REVIEW

**Comment by certik** [comment]
This looks good. It's like 1 + 0.2, then you also lose the exact number and the result becomes a float. i think that's totally fine.

**Comment by certik** [comment]
+1 to merge if tests pass.

**Comment by isuruf** [comment]
Added Python wrappers for `ComplexDouble`

**Comment by certik** [comment]
+1

**Pull request merged**
