### PR TITLE
Eval Double

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
I think the current solution is fine. It essentially always returns a complex value, but if you know that the answer is real, it uses real arithmetic, which is faster. Since we are returning a subclass of `Basic`, we can easily use complex or real answers.

This is in contrast with `EvalRealDoubleVisitor` and `EvalComplexDoubleVisitor` where you need to know the type of the answer.

**Comment by isuruf** [comment]
@certik, what do you mean by current solution? Master or this PR?

**Comment by certik** [comment]
I meant the solution in this PR is fine with me.

**Comment by isuruf** [comment]
Added some tests

**Comment by isuruf** [comment]
This is ready for review

**Comment by certik** [comment]
That looks good to me, +1.

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
