### PR TITLE
Fix a bug in subs(), add test

### PR DESCRIPTION
**Pull request by certik**
The test fails in master and this patch fixes it.

### CODE REVIEW

**Comment by certik** [comment]
This was a nasty bug, that took me several hours of hard work to debug. It manifested by evaluating the bicycle expression from @moorepants differently than sympy and the expression has 300,000 characters when printed, so it took me forever to bisect it until I nailed it. The fix was simple and things now seem to work.

**Comment by moorepants** [comment]
This silly bicycle seems to love to find bugs :smile:.

**Comment by isuruf** [comment]
+1

One other issue I see is that `p.second` and `coef` are not used in the subs.
`(2 + x*2).sub({2: y})` would still be `2+x*2`

**Comment by certik** [comment]
Thanks. I created a new issue #557 for the problem you mentioned. I don't think it returns wrong results, it's just not as powerful as it could be.

**Pull request merged**
