### PR TITLE
Move src->symengine

### PR DESCRIPTION
**Pull request by isuruf**
Header inclusion were changed from `#include 'basic.h'` to `#include <symengine/basic.h>` to avoid polluting the install directory.

For this to work in the source directory (in tree build) `src` was renamed to `symengine` and python wrappers of `symengine` moved to `symengine/python`

### CODE REVIEW

**Comment by isuruf** [comment]
This is working now. Only issue is that in-tree testing is not working as there is a folder called `symengine` (source folder) which is unrelated.

**Comment by certik** [comment]
Great job.

Why do you sometimes use symengine/header.h and sometimes just header.h?

**Comment by isuruf** [comment]
I must have missed those header.h. Which file are they in?

**Comment by certik** [comment]
I am questioning a change like this one: https://github.com/isuruf/symengine/commit/0d8abd9162d7a9fea013ce040195198bb52af314#diff-a4cefa86dcb2c8f6a4788e06ada60f0e I am sure you had a reason, but I just want to understand the issue better.

**Comment by isuruf** [comment]
That one, I had mistakenly added changed `arb.h` to `symengine/arb.h`. `arb.h` is not part of `symengine`. It is a header file from `arb`

**Comment by certik** [comment]
Ah, that's right, I didn't realize that.

**Comment by certik** [comment]
So the C++ tests work great. As to Python tests, I would execute them from the symengine/python directory. In other words, I would literally just move the `symengine` directory from master into `symengine/python/symengine`. Then things should work.

**Comment by isuruf** [comment]
What about `setup.py`? Should it be kept at the root or moved?

**Comment by certik** [comment]
Good point. Is it possible to make it work where it is? If not, I would move it.

**Comment by isuruf** [comment]
Yes, it is possible. I'll keep it at the root.

**Comment by isuruf** [comment]
PR is ready now

**Comment by certik** [comment]
@isuruf Thanks! I merged #414 first as it got finished before this PR. Would you mind merging with master by moving the src/ruby into symengine/ruby as well? It shouldn't be difficult. I'll wait with merging other PRs until this is in. Sorry about that.

**Comment by isuruf** [comment]
Rebased on top of master.

**Comment by certik** [comment]
This looks good. Tests pass on Travis, merging. Thanks for the work @isuruf!

**Pull request merged**
