### PR TITLE
Support x64 and Release Mode in MSVC

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Are we building static or dynamic libraries? I think we are building static libraries. I think there might be a way to avoid setting the compiler flags by hand, by telling cmake to build a proper library. But we can figure that out later once this is in, so that we can easily test it in all configurations.

**Comment by isuruf** [comment]
Cython installation fails with Python3.4, MinGW-w64 and Debug Mode.
Using Python2.7 instead.

We are using static libraries

**Comment by isuruf** [comment]
Since we are testing with this configuration, how about adding the flags to `UserOverride.cmake`?

**Comment by certik** [comment]
Couple comments:

* What flags do you want to put into `UserOverride.cmake`?

* Cython should not be compiled when installing, we used to do that in SymEngine: `pip install --install-option="--no-cython-compile" cython`, but it got reverted in c727d12ce00f8631e87f806ca860d4b6bf5fc521. The reason is that sometimes the compilation fails, as you noticed in mingw as well.

* It seems all we need is to test the Debug/Release mode of the C++ code (also within Python, but it doesn't matter which Python version, since all of them should be exercising the underlying C++ code in the same way).

**Comment by certik** [comment]
I think this is fine to merge as it is. We can always improve upon it later.

**Comment by isuruf** [comment]
`/MT /W1 /O2 /Ob2 /D NDEBUG` for `Release` and `/D_DEBUG /MTd /Zi /Ob0 /Od /RTC1 /W1` for `Debug`. These are just the default flags with `/MT and /W1`

I will revert to the way that cython was installed before `c727d12`

**Comment by certik** [comment]
Let's look at the flags -- what are the default cmake values? If I remember well, the only issue was with the `/MTd` related flags. I wonder why the default cmake flags do not work.

**Comment by isuruf** [comment]
`/MD /O2 /Ob2 /D NDEBUG` for Release and 
`/D_DEBUG /MD /Zi /Ob0 /Od /RTC1` for Debug are the release values.

Default values do not work because `MPIR` was compiled with `/MT` and by default symengine is compiled with `/MD`. These two are incompatible

**Comment by certik** [comment]
Actually, MPIR is compiled with `/MTd` in Debug and `/MT` in Release. The `d` is important, I think it didn't link without it either.

**Comment by isuruf** [comment]
Yes, `/MTd` is needed for Debug build.

**Comment by certik** [comment]
There is some background info on `/MT` and `/MD` here: http://stackoverflow.com/questions/757418/should-i-compile-with-md-or-mt

I would hope that CMake had some options to change this, since it seems there is no solution that fits all.

**Pull request merged**
