### PR TITLE
Changed rcp(new(symbol("*") to symbol("*") in tests

### PR DESCRIPTION
**Pull request by Sumith1896**
Following
```
RCP<const Basic> x = rcp(new Symbol("x"));
RCP<const Basic> x = rcp(new Integer(2));
```
were converted to
```
RCP<const Basic> x = symbol("x");
RCP<const Basic> x = integer(2);
```
cc @certik @isuruf

### CODE REVIEW

**Comment by abinashmeher999** [comment]
@Sumith1896 Could you please tell me why was this done?

**Comment by isuruf** [comment]
+1, Can you rebase this on top of master? Also there's some benchmarks and source files that needs to be changed as well.
@abinashmeher999, we should use the `symbol` method and avoid using `new` keyword everywhere, so that it's easier to check whether it is correct.

**Comment by certik** [comment]
Abinash, see also the gitter conversation.

**Comment by isuruf** [comment]
I'm +1 to merge

**Comment by abinashmeher999** [comment]
Seems to good to me too. +1

**Comment by certik** [comment]
Thanks @Sumith1896 for the thorough patch, +1 from me as well. Thanks @isuruf and @abinashmeher999 for the review. merging.

**Pull request merged**
