### PR TITLE
Asserting updated to == instead of = (assignment)

### PR DESCRIPTION
**Pull request by Sumith1896**
A `SYMENGINE_ASSERT` [statement](https://github.com/sympy/symengine/blob/bbe3c9baf653d18d37e3bfcd424e0781786098c1/symengine/dense_matrix.cpp#L623) in `matrix.cpp` was using assignment `=` instead of bool check `==`.

### CODE REVIEW

**Comment by certik** [comment]
+1

**Comment by Sumith1896** [comment]
Travis passes here though: https://travis-ci.org/Sumith1896/csympy/builds/69129887

**Comment by isuruf** [comment]
That is probably due to changing our test infrastructure after this PR was sent. I restarted the tests

**Comment by Sumith1896** [comment]
Thanks @isuruf

**Comment by isuruf** [comment]
It's not working. Can you do a rebase on top of master?

**Comment by certik** [comment]
Yeah, it's probably using the .travis.yml from this PR or something.

**Comment by Sumith1896** [comment]
Done, let's wait for the tests.

**Comment by Sumith1896** [comment]
Thanks for merging!

**Pull request merged**
