### PR TITLE
Improve python wrappers for matrix

### PR DESCRIPTION
**Pull request by isuruf**
Add bounds checking for `get`, `set` and `submatrix`. Previous methods are renamed to `_get`, `_set`, `_submatrix` respectively.

Also operator overloads for *, + and indexing added.

### CODE REVIEW

**Comment by certik** [comment]
Looks good, but thorough tests must be added.

**Comment by isuruf** [comment]
Added tests.

**Comment by certik** [comment]
Looks good to me.

**Comment by isuruf** [comment]
I thought I could add more methods, like pow, but those have to be implemented in C++.

**Comment by certik** [comment]
Yes, that needs to be done in C++ first. 

+1 to merge as it is.

**Pull request merged**
