### PR TITLE
Use IMPORTED targets to force cmake to use full paths

### PR DESCRIPTION
**Pull request by isuruf**
Discussion at https://gitter.im/sympy/symengine?at=55c785047f578b465ff46f30

### CODE REVIEW

**Comment by certik** [comment]
Looks like the primesieve library couldn't be found/loaded in the tests.

**Comment by isuruf** [comment]
Fixed

**Comment by certik** [comment]
I checked local installation as well as in Sage using spkg, and so far everything works as expected. Thanks @isuruf.

Let's wait if AppVeyor passes as well before merging.

**Comment by certik** [comment]
Tests pass, merging.

**Pull request merged**
