### PR TITLE
Create SymEngineConfig.cmake to use symengine from other projects

### PR DESCRIPTION
**Pull request by isuruf**
I followed the following links to do this. (At least the parts I understood)

http://www.cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file
http://www.cmake.org/cmake/help/v3.2/manual/cmake-packages.7.html
http://www.cmake.org/cmake/help/v3.0/command/find_package.html

Now you can include symengine with just `find_package(SymEngine CONFIG Paths /path)` where path is the symengine installation directory or the build directory.

### CODE REVIEW

**Comment by isuruf** [comment]
Travis CI fails due to missing 

But the documentation says it's there, http://www.cmake.org/cmake/help/v2.8.7/cmake.html#command:find_package

**Comment by certik** [comment]
I think this looks good, though I need to test it some more by hand.

**Comment by isuruf** [comment]
I have made the python wrappers a separate CMake project. To build with the main repo you can add `-DWITH_PYTHON=yes` as before or else you can do `cmake -DSYMENGINE_DIR=/path/to/symengine/install` separately on the python directory

**Comment by certik** [comment]
This is awesome, thanks for the work!

**Comment by isuruf** [comment]
@certik, this is now ready for review. 
`SymEngineConfig.cmake` is tested at two different places now. In python and ruby wrappers where the build tree configuration is tested and in https://github.com/isuruf/symengine/blob/88e3928c8a6a7590eda51a9e21186ac3d88ae3f3/bin/test_travis.sh#L119 where the install directory configuration is tested

**Comment by certik** [comment]
I think it looks pretty good. Let me test it by hand a bit.

**Comment by certik** [comment]
I tested it by hand, and reviewed the PR, it seems it works well and all tests pass. Thanks for the work!

**Pull request merged**
