### PR TITLE
Added AMiT to AUTHORS. Welcome to SymEngine!

### PR DESCRIPTION
**Pull request by Sumith1896**
@aktech Could you check and let me know if any changes needed?

### CODE REVIEW

**Comment by aktech** [comment]
Looks great. +1
Thanks!

-----Original Message-----

**Comment by certik** [comment]
@Sumith1896 why don't you change the commit text from CSymPy to SymEngine as well. :) I'll merge after that.

**Comment by certik** [comment]
I see, you just did. Thanks!

**Comment by Sumith1896** [comment]
Will take some time for SymEngine to sink in.

**Comment by aktech** [comment]
BTW, forgot to ask does this (my name) also needs to be added to .mailmap?

**Comment by Sumith1896** [comment]
AFAIK If commits with different user names or user mails, then yes.
As of now, all commits correspond to you, so not needed.

**Comment by aktech** [comment]
Thanks @Sumith1896 for enlightening me on this :) .

**Pull request merged**
