### PR TITLE
Add Catch as a testing library

### PR DESCRIPTION
**Pull request by isuruf**
Some changes
- Use docker for travis testing
- Remove -Werror in testing in clang on linux due to weird bug in system headers.

### CODE REVIEW

**Comment by certik** [comment]
If tests pass, +1 to merge as it is.

**Comment by certik** [comment]
I think this broke Shippable builds completely. We can perhaps ignore Shippable for now and fix it later, I think there were more issues with Shippable.

**Comment by certik** [comment]
+1. Let's get this merged in some form that passes tests, so that we can move on.

**Comment by isuruf** [comment]
Shippable passes. Travis tests haven't started yet.

**Comment by certik** [comment]
Travis succeeded for ecb0557. @isuruf why don't you merge that one and send a new PR for the rest?

The point is that we can then start rebasing the other PRs and start testing them. The change in the last 3 patches is very minor, so that can be merged as a separate PR.

Otherwise we need to wait for another day or so.

**Comment by isuruf** [comment]
Sure. 300b75a shouldn't affect travis right?

**Comment by certik** [comment]
No, but the other patches can.

**Comment by isuruf** [comment]
Done

**Comment by certik** [comment]
Thanks!!

**Comment by certik** [comment]
We can start merging other PRs now.

**Comment by Sumith1896** [comment]
Thanks @isuruf for all the work here. Good job :+1:

**Pull request merged**
